######################################################################
# Automatically generated by qmake (2.01a) sab ago 29 03:10:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += phonon

# Input
HEADERS += player.h
SOURCES += main.cc player.cc
